### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by miko91** [FokkeZB/nl.fokkezb.pullToRefresh#39] opened 2015-02-21 15:21 UTC
Hi,

I follow steps in ReadMe. The view contains an empty TableView that is filled with myRefresher function. Without the widget the loadAllNews function works fine. The module is installed. I installed the widget with gittio.

### View
```javascript
<Alloy>
	<Widget id="ptr" src="nl.fokkezb.pullToRefresh" onRelease="myRefresher">
		<TableView id="newsList" backgroundcolor="#f1f2ef">
		</TableView>
	</Widget>
</Alloy>
```

### Controller
```javascript
var loadAllNews = function() {
	var loaderArgs = {
		callbackFunction : callBackLoadAllNews,
		url              : Alloy.CFG.Urls.baseURL + Alloy.CFG.Urls.getAllNews 
	};
	loader.get(loaderArgs);
};

var callBackLoadAllNews = function(argsNews) {
	if(argsNews != null) {
		Ti.API.log(argsNews);
		$.newsList.setData([]);
		$.newsList.removeAllChildren();
		var rows = [];
		for (var i = 0; i < argsNews.result; ++i)
		{
			var row = Alloy.createController("newsRow", argsNews.data[i]).getView("newsItem");
			rows.push(row);
		}
		$.newsList.setData(rows);
	}
};

function myRefresher(e) {
	loadAllNews();
	e.hide();
}

$.ptr.refresh();
```

### Log
```
[WARN] :   dalvikvm: threadid=1: thread exiting with uncaught exception (group=0xb0d72b20)
[ERROR] :  TiApplication: (main) [16292,16292] Sending event: exception on thread: main msg:java.lang.ClassCastException: java.util.HashMap cannot be cast to org.appcelerator.titanium.proxy.TiViewProxy; Titanium 3.5.0,2015/01/12 15:33,0014f83
[ERROR] :  TiApplication: java.lang.ClassCastException: java.util.HashMap cannot be cast to org.appcelerator.titanium.proxy.TiViewProxy
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleMessage(TiViewProxy.java:230)
[ERROR] :  TiApplication: 	at android.os.Handler.dispatchMessage(Handler.java:98)
[ERROR] :  TiApplication: 	at android.os.Looper.loop(Looper.java:136)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.main(ActivityThread.java:5017)
[ERROR] :  TiApplication: 	at java.lang.reflect.Method.invokeNative(Native Method)
[ERROR] :  TiApplication: 	at java.lang.reflect.Method.invoke(Method.java:515)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
[ERROR] :  TiApplication: 	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by FokkeZB** [comment] 2015-02-21 16:55
I'm not sure if it will fix your issue, but there are some things wrong in your controller code. See this improved (but unchecked) version.

- No need to empty the table or removeAllChildren if you call setData.
- Wait to call e.done() until data has actually loaded/rendered
- Call e.done() only if there's no more data to load

See readme for more info.

```
function myRefresher(e) {
  loader.get({
    callbackFunction: function(argsNews) {
      if (argsNews !== null) {
        var rows = [];
        for (var i = 0; i < argsNews.result; ++i) {
          var row = Alloy.createController("newsRow", argsNews.data[i]).getView("newsItem");
          rows.push(row);
        }
        $.newsList.setData(rows);
        e.hide(); // or call e.done() if there are no more rows
      } else {
        e.error();
      }
    },
    url: Alloy.CFG.Urls.baseURL + Alloy.CFG.Urls.getAllNews
  });
}

$.ptr.refresh();
```

**Comment by miko91** [comment] 2015-02-21 18:41
First, thank you for this fast answer.

I tried your solution, unfortunatly it doesn't work. Il also try to remove the trigger function and the fisrt call ($.ptr.refresh()). It seems that just have the widget in the view causes the crash.

Do you have a demo app which I could check differences with mine ?

**Comment by FokkeZB** [comment] 2015-02-21 18:58
Yep, the test branch: https://github.com/FokkeZB/nl.fokkezb.pullToRefresh/tree/test

**Comment by miko91** [comment] 2015-02-21 19:38
I find a solution !

I add a Window to wrap my View, it works fine now. Thanks again.

**Comment by FokkeZB** [comment] 2015-02-21 21:15
Good one, I'll add a note the widget can't be the root element.

**Comment by miko91** [comment] 2015-02-22 13:12
In my case the widget was added to a View, already inside a Window.
It works with Window -> View -> **Window** -> Widget

**Comment by FokkeZB** [comment] 2015-02-22 18:12
WTF! That can't be right. Could you enlight me on the exact hierarchy of views and required controllers/widget?

**Comment by miko91** [comment] 2015-02-22 22:57
Don't forget I'm new in Ti.

In index I use your **drawer** module which uses Views (for Android).
I load other contents in the center view.
So in my **news** case I have View (from index, Center role) -> Window -> Widget.
Without the Window it doesn't work.

**Comment by FokkeZB** [comment] 2015-02-23 06:17
A Window should only be used a as a top level view. Replace it with a View.

Any chance you could give me access to the project so I can have a look what is going wrong?

**Comment by miko91** [comment] 2015-02-23 09:36
Hi,

There is a lite copy of my project here : https://github.com/miko91/test-widget

I was wrong about one thing, the widget should be wrapped by Window **or** View in the in the xml file. See by yourself.

**Comment by FokkeZB** [comment] 2015-03-04 11:32
Seems that you've found an Alloy bug. Without a parent view/window the news.xml compiles to:

```
    $.__views.ptr = Alloy.createWidget("nl.fokkezb.pullToRefresh", "widget", {
        id: "ptr",
        targetId: "newsList",
        children: [ $.__views.newsList ],
        __parentSymbol: __parentSymbol
    });
    $.__views.ptr && $.addTopLevelView($.__views.ptr);
```

The last line should be:

```
    $.__views.ptr && $.addTopLevelView($.__views.ptr.getView());
```

I'll create a ticket.

**Comment by FokkeZB** [comment] 2015-03-04 12:51
JIRA ticket to follow: https://jira.appcelerator.org/browse/ALOY-1256

**Comment by FokkeZB** [comment] 2015-03-04 12:51
Closing as not our bug.

**Comment by nuno** [comment] 2015-05-08 21:27
@FokkeZB, @miko91  there is a temporary fix for this situation? Im with the same issue.

**Comment by FokkeZB** [comment] 2015-05-09 05:46
Are you sure that is the same issue? In your example the widget is not the root view.

**Comment by nuno** [comment] 2015-05-09 10:47
I will make a test case, yeah not sure if is this problem or not, is hard to me read the compiler alloy files, so no better person than you to take a look :)

**Comment by nuno** [comment] 2015-05-10 11:27
As I can see  the man issue is 
```nl.fokkezb.pullToRefresh``` with ```kr.yostudio.drawer```   and ```CollectionView Module``` 
If remove the ```<Widget id="ptr" src="nl.fokkezb.pullToRefresh" onRelease="myRefresher">``` part works ok, can be the problem widget inside widgets, @FokkeZB ?

**Comment by FokkeZB** [comment] 2015-05-10 13:43
Widgets in widgets should be fine. It's just controllers. But there can be troubles with toplevel selection.

I'd suggest making a minimal test case that reproduces and then drop it somewhere including `Resources` so we can investigate the compiled source code for errors.

**Comment by nuno** [comment] 2015-05-10 15:21
Since when the order or modules in tiapp.xml is very very important?

Where is comment out not work, the other block just works.


The order is important?
```
    <modules>
        <module platform="iphone">de.marcelpociot.collectionview</module>
        <module platform="android">de.marcelpociot.collectionview</module>
        <module platform="android">com.rkam.swiperefreshlayout</module>
        <module platform="android">com.tripvi.drawerlayout</module>
    </modules>
    <!--  <modules>
        <module platform="android">com.tripvi.drawerlayout</module>
        <module platform="android">com.rkam.swiperefreshlayout</module>
        <module platform="android">de.marcelpociot.collectionview</module>
        <module platform="iphone">de.marcelpociot.collectionview</module>
    </modules> -->

```

**Comment by FokkeZB** [comment] 2015-05-10 16:09
For Android it might be important indeed and you should see messages about conflicting (duplicate) resources in the different JAR files in that case.

**Closed by FokkeZB** 2015-05-10 16:09 UTC
Labels: invalid
